//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAgenda.Resources.Events {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Create {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevAgenda.Resources.Events.Create", typeof(Create).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new event.
        /// </summary>
        public static string AddNewEvent {
            get {
                return ResourceManager.GetString("AddNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event end date. Leave empty for one-day events..
        /// </summary>
        public static string EndDateTooltipContent {
            get {
                return ResourceManager.GetString("EndDateTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of event it is? Is it free of charge for attendees?.
        /// </summary>
        public static string IsFreeOfChargeTooltipContent {
            get {
                return ResourceManager.GetString("IsFreeOfChargeTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search powered by Google Maps..
        /// </summary>
        public static string LocationNotes {
            get {
                return ResourceManager.GetString("LocationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City where the event is held. Type in a city name and choose one from suggestions below..
        /// </summary>
        public static string LocationTooltipContent {
            get {
                return ResourceManager.GetString("LocationTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should be a full name of the event or a meaningful abbreviation. Please provide edition year wherever appropriate, i.e. PDC 2012..
        /// </summary>
        public static string NameTooltipContent {
            get {
                return ResourceManager.GetString("NameTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date when the event starts or is held..
        /// </summary>
        public static string StartDateTooltipContent {
            get {
                return ResourceManager.GetString("StartDateTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain text only..
        /// </summary>
        public static string SummaryNotes {
            get {
                return ResourceManager.GetString("SummaryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick summary of the event or any information about the event that is not included in the other fields but is still important..
        /// </summary>
        public static string SummaryTooltipContent {
            get {
                return ResourceManager.GetString("SummaryTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces as separators..
        /// </summary>
        public static string TagsNotes {
            get {
                return ResourceManager.GetString("TagsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags that describes the event well. Try to use more general tags i.e. &quot;.net&quot;, &quot;smart-phones&quot; where possible..
        /// </summary>
        public static string TagsTooltipContent {
            get {
                return ResourceManager.GetString("TagsTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter hashtag where the discussion about the event is being held..
        /// </summary>
        public static string TwitterHashTagTooltipContent {
            get {
                return ResourceManager.GetString("TwitterHashTagTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Twitter profile of the event..
        /// </summary>
        public static string TwitterProfileTooltipContent {
            get {
                return ResourceManager.GetString("TwitterProfileTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of event it is? Is it free of charge for attendees?.
        /// </summary>
        public static string TypeIdTooltipContent {
            get {
                return ResourceManager.GetString("TypeIdTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to the official website of the event..
        /// </summary>
        public static string WebsiteTooltipContent {
            get {
                return ResourceManager.GetString("WebsiteTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to provide?.
        /// </summary>
        public static string WhatToProvideHeader {
            get {
                return ResourceManager.GetString("WhatToProvideHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///      All possible information about an event are not needed. Just &lt;strong&gt;when, where&lt;/strong&gt; and &lt;strong&gt;why&lt;/strong&gt;.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///      Fields like Twitter hashtag or summary are not obligatory but if provided they bring much more information to the table.
        ///    &lt;/p&gt;.
        /// </summary>
        public static string WhatToProvideTextBlock {
            get {
                return ResourceManager.GetString("WhatToProvideTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why bother?.
        /// </summary>
        public static string WhyBotherHeader {
            get {
                return ResourceManager.GetString("WhyBotherHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///      By adding new event you allow your fellow developers to find out about it more easily.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///      The more developers know about an event the more they are likely to come.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///      You do not have to be a host to add an event. &lt;strong&gt;Do it&lt;/strong&gt; for the others. &lt;strong&gt;Benefits&lt;/strong&gt; are outright.
        ///    &lt;/p&gt;.
        /// </summary>
        public static string WhyBotherTextBlock {
            get {
                return ResourceManager.GetString("WhyBotherTextBlock", resourceCulture);
            }
        }
    }
}
